import { ChevronDown } from "lucide-react";
import { useState } from "react";
import SiteHeader from "../../components/layout/SiteHeader";
import SiteFooter from "../../components/layout/SiteFooter";
import SharedBottomCtaSection from "../../components/sections/SharedBottomCtaSection";
import "./FaqPage.css";

const faqGroups = [{ title: "Service & Coverage", items: [{ question: "What Areas Do You Cover?", answer: "We offer national coverage across the UK, spanning over 1,100 towns and cities. From major cities like London, Manchester, and Birmingham to smaller towns, our network of licensed teams is ready to help." }, { question: "How Quickly Can You Collect My Rubbish?", answer: "Same-day and next-day slots are often available depending on your location, access, and team schedule." }, { question: "Do I Need To Be At Home For The Collection?", answer: "Not always. If access is arranged and waste is clearly identified, some jobs can go ahead without you being present." }, { question: "What Are Your Operating Hours?", answer: "We run collections throughout the week and offer flexible slots to fit homes, landlords, and businesses." }] }, { title: "Pricing & Quotes", items: [{ question: "How Does Your Pricing Work?", answer: "Pricing is based on load size, access, and waste type. We give you a clear fixed quote before collection starts." }, { question: "How Do I Get An Accurate Quote?", answer: "Send photos, describe the items, or use our quote form so we can recommend the right load size and price." }, { question: "Are Parking Fees Included In The Price?", answer: "Standard pricing covers collection and disposal, but restricted parking or unusual access may need to be confirmed beforehand." }, { question: "How Do I Pay?", answer: "We accept major payment methods and can confirm the best option when you book." }] }, { title: "What We Take", items: [{ question: "What Types Of Waste Do You NOT Take?", answer: "Hazardous waste, asbestos, gas bottles, chemicals, and certain restricted materials need specialist disposal." }, { question: "Do You Take Large Bulky Items Like Sofas And White Goods?", answer: "Yes. Sofas, wardrobes, appliances, mattresses, and other bulky household items are all common collections." }, { question: "Do You Handle Commercial And Office Clearances?", answer: "Yes. We collect office furniture, shop fittings, packaging waste, and mixed commercial rubbish." }, { question: "Do I Need To Leave My Rubbish Outside?", answer: "No. Our teams can collect from inside the property if access is safe and agreed in advance." }] }];
function FaqRow({ item, isOpen, onToggle }) { return (<article className={`faq-page__item ${isOpen ? "faq-page__item--open" : ""}`}><button type="button" className="faq-page__summary" onClick={onToggle}><span>{item.question}</span><ChevronDown size={18} className={`faq-page__icon ${isOpen ? "faq-page__icon--open" : ""}`} /></button>{isOpen ? <p className="faq-page__answer">{item.answer}</p> : null}</article>); }
export default function FaqPage() { const [openKey, setOpenKey] = useState("0-0"); return (<><SiteHeader /><main className="faq-page"><section className="faq-page__hero"><div className="page-shell faq-page__hero-inner"><p className="section-eyebrow">Got Questions?</p><h1 className="faq-page__title">Frequently Asked Questions</h1><p className="faq-page__subtitle">Everything you need to know about our service, pricing, and coverage.</p></div></section><section className="faq-page__groups"><div className="page-shell">{faqGroups.map((group, groupIndex) => (<div key={group.title} className="faq-page__group"><h2 className="faq-page__group-title">{group.title}</h2><div className="faq-page__list">{group.items.map((item, itemIndex) => { const key = `${groupIndex}-${itemIndex}`; return (<FaqRow key={item.question} item={item} isOpen={openKey === key} onToggle={() => setOpenKey((current) => (current === key ? "" : key))} />); })}</div></div>))}</div></section><SharedBottomCtaSection title="Still Have Questions?" text="Our 2026 customer support team is here to help you coordinate your waste clearance seamlessly." /><SiteFooter /></main></>); }
